<?xml version="1.0" encoding="UTF-8"?>
<!--- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Legal Notices

SWIFT SCRL@2016. All rights reserved.

This schema is a component of MyStandards, the SWIFT collaborative Web application used to manage
standards definitions and industry usage.

This is a licensed product, which may only be used and distributed in accordance with MyStandards License
Terms as specified in MyStandards Service Description and the related Terms of Use.

Unless otherwise agreed in writing with SWIFT SCRL, the user has no right to:
 - authorise external end users to use this component for other purposes than their internal use.
 - remove, alter, cover, obfuscate or cancel from view any copyright or other proprietary rights notices appearing in this physical medium.
 - re-sell or authorise another party e.g. software and service providers, to re-sell this component.

This component is provided 'AS IS'. SWIFT does not give and excludes any express or implied warranties
with respect to this component such as but not limited to any guarantee as to its quality, supply or availability.

Any and all rights, including title, ownership rights, copyright, trademark, patents, and any other intellectual 
property rights of whatever nature in this component will remain the exclusive property of SWIFT or its 
licensors.

Trademarks
SWIFT is the trade name of S.W.I.F.T. SCRL.
The following are registered trademarks of SWIFT: the SWIFT logo, SWIFT, SWIFTNet, SWIFTReady, Accord, Sibos, 3SKey, Innotribe, the Standards Forum logo, MyStandards, and SWIFT Institute.
Other product, service, or company names in this publication are trade names, trademarks, or registered trademarks of their respective owners.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Group: Cross Border Payments and Reporting Plus (CBPR+)
Collection: CBPRPlus_ISO 20022 Portfolio_November 2022_Release 2.1
Usage Guideline: CBPRPlus-pain.002.001.10_CustomerPaymentStatusReport
Base Message: pain.002.001.10
Date of publication: 29 December 2021
URL: https://www2.swift.com/mystandards/#/mp/mx/_ImGiIFKDEeyXX57HMRFmxw/_XC3TMV9CEeyfdsiuljUhuQ
Description: Principles:

1. The CustomerPaymentStatusReport message is sent by the Initiating party to the previous agent in the payment chain. 

2. The pain.002 usage to provide notification of a rejected (negative) status is required by all agents, whereas the usage to provide a positive status will always be governed by a bilateral agreement between the agents.

3. Character Set:
All proprietary and Text fields EXCLUDING Name and Address for all actors and Related Remittance Information and Remittance are limited to the FIN-X-Character set.

All Name and Address for all actors, Related Remittance Information and Remittance Information (structured and unstructured), Email Address where included as part of a proxy element are extended to support the following additional characters:

  !#$&%*=^_’{|}~";<>@[\]

< is replaced with &lt;
> is replaced with &gt;

Generated by the MyStandards web platform [https://www.swift.com/mystandards] on 2022-05-23T17:36:46+00:00
-->
<!---->
<xs:schema xmlns="urn:iso:std:iso:20022:tech:xsd:pain.002.001.10" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.10">
    <xs:element name="Document" type="Document"/>
    <xs:simpleType name="AnyBICDec2014Identifier">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">AnyBICDec2014Identifier</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Code allocated to a financial or non-financial institution by the ISO 9362 Registration Authority, as described in ISO 9362: 2014 - "Banking - Banking telecommunication messages - Business identifier code (BIC)".</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z0-9]{4,4}[A-Z]{2,2}[A-Z0-9]{2,2}([A-Z0-9]{3,3}){0,1}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="BICFIDec2014Identifier">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">BICFIDec2014Identifier</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Code allocated to a financial institution by the ISO 9362 Registration Authority as described in ISO 9362: 2014 - "Banking - Banking telecommunication messages - Business identifier code (BIC)".</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z0-9]{4,4}[A-Z]{2,2}[A-Z0-9]{2,2}([A-Z0-9]{3,3}){0,1}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="BranchAndFinancialInstitutionIdentification6__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">BranchAndFinancialInstitutionIdentification6__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Unique and unambiguous identification of a financial institution or a branch of a financial institution.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="FinInstnId" type="FinancialInstitutionIdentification18__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">FinancialInstitutionIdentification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Unique and unambiguous identification of a financial institution, as assigned under an internationally recognised or proprietary identification scheme.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="CBPR_RestrictedFINXMax35Text">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">CBPR_RestrictedFINXMax35Text</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Specifies a character string with a minimum length of 1, and a maximum length of 35 characters, and limited to character set X, that is, 0-9 a-z A-Z / - ? : ( ) . , ‘ + .</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9a-zA-Z/\-\?:\(\)\.,'\+ ]+"/>
            <xs:minLength value="1"/>
            <xs:maxLength value="35"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="ClearingSystemIdentification2Choice__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">ClearingSystemIdentification2Choice__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Choice of a clearing system identifier.</xs:documentation>
        </xs:annotation>
        <xs:choice>
            <xs:element name="Cd" type="ExternalClearingSystemIdentification1Code">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Code</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Identification of a clearing system, in a coded form as published in an external list.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="ClearingSystemMemberIdentification2__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">ClearingSystemMemberIdentification2__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Unique identification, as assigned by a clearing system, to unambiguously identify a member of the clearing system.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="ClrSysId" type="ClearingSystemIdentification2Choice__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">ClearingSystemIdentification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Specification of a pre-agreed offering between clearing agents or the channel through which the payment instruction is processed.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="MmbId" type="Max35Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">MemberIdentification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Identification of a member of a clearing system.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="CountryCode">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">CountryCode</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Code to identify a country, a dependency, or another area of particular geopolitical interest, on the basis of country names obtained from the United Nations (ISO 3166, Alpha-2 code).</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]{2,2}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="CustomerPaymentStatusReportV10">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">CustomerPaymentStatusReportV10</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Scope&#13;
The CustomerPaymentStatusReport message is sent by an instructed agent to the previous party in the payment chain. It is used to inform this party about the positive or negative status of an instruction (either single or file). It is also used to report on a pending instruction.&#13;
Usage&#13;
The CustomerPaymentStatusReport message is exchanged between an agent and a non-financial institution customer to provide status information on instructions previously sent. Its usage will always be governed by a bilateral agreement between the agent and the non-financial institution customer.&#13;
The CustomerPaymentStatusReport message can be used to provide information about the status (for example a rejection, an acceptance) of the initiation of a credit transfer, a direct debit, as well as on the initiation of other customer instructions.&#13;
The CustomerPaymentStatusReport message refers to the original instruction(s) by means of references only or by means of references and a set of elements from the original instruction.&#13;
The CustomerPaymentStatusReport message can be used in domestic and cross-border scenarios.&#13;
The CustomerPaymentStatusReport may also be sent to the receiver of the payment in a real time payment scenario, as both sides of the transactions must be informed of the status of the transaction (that is either the beneficiary is credited, or the transaction is rejected).</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="GrpHdr" type="GroupHeader86__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">GroupHeader</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Set of characteristics shared by all individual transactions included in the status report message.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="OrgnlGrpInfAndSts" type="OriginalGroupHeader17__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">OriginalGroupInformationAndStatus</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Original group information concerning the group of transactions, to which the status report message refers to.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="OrgnlPmtInfAndSts" type="OriginalPaymentInstruction32__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">OriginalPaymentInformationAndStatus</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Information concerning the original payment information, to which the status report message refers.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="DateAndPlaceOfBirth1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">DateAndPlaceOfBirth1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Date and place of birth of a person.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="BirthDt" type="ISODate">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">BirthDate</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Date on which a person is born.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="PrvcOfBirth" type="Max35Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">ProvinceOfBirth</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Province where a person was born.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="CityOfBirth" type="Max35Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">CityOfBirth</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">City where a person was born.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="CtryOfBirth" type="CountryCode">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">CountryOfBirth</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Country where a person was born.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Document">
        <xs:sequence>
            <xs:element name="CstmrPmtStsRpt" type="CustomerPaymentStatusReportV10"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="ExternalClearingSystemIdentification1Code">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">ExternalClearingSystemIdentification1Code</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Specifies the clearing system identification code, as published in an external clearing system identification code list.&#13;
External code sets can be downloaded from www.iso20022.org.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="5"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="ExternalOrganisationIdentification1Code">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">ExternalOrganisationIdentification1Code</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Specifies the external organisation identification scheme name code in the format of character string with a maximum length of 4 characters.&#13;
The list of valid codes is an external code list published separately.&#13;
External code sets can be downloaded from www.iso20022.org.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="4"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="ExternalPaymentTransactionStatus1Code">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">ExternalPaymentTransactionStatus1Code</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Specifies the status of an individual payment instructions, as published in an external payment transaction status code set.&#13;
External code sets can be downloaded from www.iso20022.org.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="4"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="ExternalPersonIdentification1Code">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">ExternalPersonIdentification1Code</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Specifies the external person identification scheme name code in the format of character string with a maximum length of 4 characters.&#13;
The list of valid codes is an external code list published separately.&#13;
External code sets can be downloaded from www.iso20022.org.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="4"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="ExternalStatusReason1Code">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">ExternalStatusReason1Code</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Specifies the status reason, as published in an external status reason code list.&#13;
External code sets can be downloaded from www.iso20022.org.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="4"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="FinancialInstitutionIdentification18__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">FinancialInstitutionIdentification18__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Specifies the details to identify a financial institution.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="BICFI" type="BICFIDec2014Identifier">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">BICFI</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Code allocated to a financial institution by the ISO 9362 Registration Authority as described in ISO 9362 "Banking - Banking telecommunication messages - Business identifier code (BIC)".</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="ClrSysMmbId" type="ClearingSystemMemberIdentification2__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">ClearingSystemMemberIdentification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Information used to identify a member within a clearing system.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="LEI" type="LEIIdentifier">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">LEI</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Legal entity identifier of the financial institution.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="GenericOrganisationIdentification1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">GenericOrganisationIdentification1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Information related to an identification of an organisation.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="Id" type="Max35Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Identification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Identification assigned by an institution.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="SchmeNm" type="OrganisationIdentificationSchemeName1Choice">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">SchemeName</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Name of the identification scheme.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="Issr" type="Max35Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Issuer</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Entity that assigns the identification.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="GenericPersonIdentification1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">GenericPersonIdentification1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Information related to an identification of a person.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="Id" type="Max35Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Identification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Unique and unambiguous identification of a person.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="SchmeNm" type="PersonIdentificationSchemeName1Choice">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">SchemeName</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Name of the identification scheme.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="Issr" type="Max35Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Issuer</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Entity that assigns the identification.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="GroupHeader86__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">GroupHeader86__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Provides the characteristics shared by all individual transactions included in the message.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="MsgId" type="CBPR_RestrictedFINXMax35Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">MessageIdentification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Point to point reference, as assigned by the instructing party, and sent to the next party in the chain to unambiguously identify the message.
Usage: The instructing party has to make sure that 'MessageIdentification' is unique per instructed party for a pre-agreed period.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="CreDtTm" type="ISODateTime">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">CreationDateTime</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Date and time at which the message was created.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="InitgPty" type="PartyIdentification135__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">InitiatingParty</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Party that initiates the status message.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="FwdgAgt" type="BranchAndFinancialInstitutionIdentification6__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">ForwardingAgent</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Financial institution that receives the instruction from the initiating party and forwards it to the next agent in the payment chain.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="ISODate">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">ISODate</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">A particular point in the progression of time in a calendar year expressed in the YYYY-MM-DD format. This representation is defined in "XML Schema Part 2: Datatypes Second Edition - W3C Recommendation 28 October 2004" which is aligned with ISO 8601.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:date"/>
    </xs:simpleType>
    <xs:simpleType name="ISODateTime">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">ISODateTime</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">A particular point in the progression of time defined by a mandatory date and a mandatory time component, expressed in either UTC time format (YYYY-MM-DDThh:mm:ss.sssZ), local time with UTC offset format (YYYY-MM-DDThh:mm:ss.sss+/-hh:mm), or local time format (YYYY-MM-DDThh:mm:ss.sss). These representations are defined in "XML Schema Part 2: Datatypes Second Edition - W3C Recommendation 28 October 2004" which is aligned with ISO 8601.
Note on the time format:
1) beginning / end of calendar day
00:00:00 = the beginning of a calendar day
24:00:00 = the end of a calendar day
2) fractions of second in time format
Decimal fractions of seconds may be included. In this case, the involved parties shall agree on the maximum number of digits that are allowed.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:dateTime"/>
    </xs:simpleType>
    <xs:simpleType name="LEIIdentifier">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">LEIIdentifier</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Legal Entity Identifier is a code allocated to a party as described in ISO 17442 "Financial Services - Legal Entity Identifier (LEI)".</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z0-9]{18,18}[0-9]{2,2}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="Max105Text">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">Max105Text</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Specifies a character string with a maximum length of 105 characters.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="105"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="Max140Text">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">Max140Text</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Specifies a character string with a maximum length of 140 characters.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="140"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="Max16Text">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">Max16Text</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Specifies a character string with a maximum length of 16 characters.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="16"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="Max35Text">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">Max35Text</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Specifies a character string with a maximum length of 35 characters.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="35"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="Max70Text">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">Max70Text</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Specifies a character string with a maximum length of 70characters.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="70"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="OrganisationIdentification29__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">OrganisationIdentification29__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Unique and unambiguous way to identify an organisation.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="AnyBIC" type="AnyBICDec2014Identifier">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">AnyBIC</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Business identification code of the organisation.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="LEI" type="LEIIdentifier">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">LEI</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Legal entity identification as an alternate identification for a party.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="2" minOccurs="0" name="Othr" type="GenericOrganisationIdentification1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Other</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Unique identification of an organisation, as assigned by an institution, using an identification scheme.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="OrganisationIdentification29__2">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">OrganisationIdentification29__2</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Unique and unambiguous way to identify an organisation.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element maxOccurs="1" minOccurs="0" name="AnyBIC" type="AnyBICDec2014Identifier">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">AnyBIC</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Business identification code of the organisation.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="LEI" type="LEIIdentifier">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">LEI</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Legal entity identification as an alternate identification for a party.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="2" minOccurs="0" name="Othr" type="GenericOrganisationIdentification1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Other</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Unique identification of an organisation, as assigned by an institution, using an identification scheme.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="OrganisationIdentificationSchemeName1Choice">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">OrganisationIdentificationSchemeName1Choice</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Sets of elements to identify a name of the organisation identification scheme.</xs:documentation>
        </xs:annotation>
        <xs:choice>
            <xs:element name="Cd" type="ExternalOrganisationIdentification1Code">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Code</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Name of the identification scheme, in a coded form as published in an external list.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="Prtry" type="Max35Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Proprietary</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Name of the identification scheme, in a free text form.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="OriginalGroupHeader17__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">OriginalGroupHeader17__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Provides details on the original group, to which the message refers.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="OrgnlMsgId" type="Max35Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">OriginalMessageIdentification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Point to point reference, as assigned by the original instructing party, to unambiguously identify the original message.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="OrgnlMsgNmId" type="Max35Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">OriginalMessageNameIdentification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Specifies the original message name identifier to which the message refers.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="OrgnlCreDtTm" type="ISODateTime">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">OriginalCreationDateTime</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Date and time at which the original message was created.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="OriginalPaymentInstruction32__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">OriginalPaymentInstruction32__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Provides details information on the original transactions, to which the status report message refers.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="OrgnlPmtInfId" type="Max35Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">OriginalPaymentInformationIdentification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Unique identification, as assigned by the original sending party, to unambiguously identify the original payment information group.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="TxInfAndSts" type="PaymentTransaction105__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">TransactionInformationAndStatus</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Provides information on the original transactions to which the status report message refers.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Party38Choice__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">Party38Choice__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Nature or use of the account.</xs:documentation>
        </xs:annotation>
        <xs:choice>
            <xs:element name="OrgId" type="OrganisationIdentification29__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">OrganisationIdentification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Unique and unambiguous way to identify an organisation.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="Party38Choice__2">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">Party38Choice__2</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Nature or use of the account.</xs:documentation>
        </xs:annotation>
        <xs:choice>
            <xs:element name="OrgId" type="OrganisationIdentification29__2">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">OrganisationIdentification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Unique and unambiguous way to identify an organisation.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="PrvtId" type="PersonIdentification13__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">PrivateIdentification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Unique and unambiguous identification of a person, for example a passport.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="PartyIdentification135__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">PartyIdentification135__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Specifies the identification of a person or an organisation.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="Id" type="Party38Choice__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Identification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Unique and unambiguous identification of a party.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="PartyIdentification135__2">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">PartyIdentification135__2</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Specifies the identification of a person or an organisation.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element maxOccurs="1" minOccurs="0" name="Nm" type="Max140Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Name</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Name by which a party is known and which is usually used to identify that party.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="PstlAdr" type="PostalAddress24__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">PostalAddress</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Information that locates and identifies a specific address, as defined by postal services.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="Id" type="Party38Choice__2">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Identification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Unique and unambiguous identification of a party.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="CtryOfRes" type="CountryCode">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">CountryOfResidence</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Country in which a person resides (the place of a person's home). In the case of a company, it is the country from which the affairs of that company are directed.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="PaymentTransaction105__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">PaymentTransaction105__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Provides further details on the original transactions, to which the status report message refers.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element maxOccurs="1" minOccurs="0" name="OrgnlInstrId" type="Max35Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">OriginalInstructionIdentification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Unique identification, as assigned by the original instructing party for the original instructed party, to unambiguously identify the original instruction.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="OrgnlEndToEndId" type="Max35Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">OriginalEndToEndIdentification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Unique identification, as assigned by the original initiating party, to unambiguously identify the original transaction.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="OrgnlUETR" type="UUIDv4Identifier">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">OriginalUETR</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Universally unique identifier to provide the original end-to-end reference of a payment transaction.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="TxSts" type="ExternalPaymentTransactionStatus1Code">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">TransactionStatus</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Specifies the status of a transaction, in a coded form.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="StsRsnInf" type="StatusReasonInformation12__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">StatusReasonInformation</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Provides detailed information on the status reason.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="PersonIdentification13__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">PersonIdentification13__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Unique and unambiguous way to identify a person.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element maxOccurs="1" minOccurs="0" name="DtAndPlcOfBirth" type="DateAndPlaceOfBirth1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">DateAndPlaceOfBirth</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Date and place of birth of a person.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="2" minOccurs="0" name="Othr" type="GenericPersonIdentification1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Other</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Unique identification of a person, as assigned by an institution, using an identification scheme.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="PersonIdentificationSchemeName1Choice">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">PersonIdentificationSchemeName1Choice</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Sets of elements to identify a name of the identification scheme.</xs:documentation>
        </xs:annotation>
        <xs:choice>
            <xs:element name="Cd" type="ExternalPersonIdentification1Code">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Code</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Name of the identification scheme, in a coded form as published in an external list.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="Prtry" type="Max35Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Proprietary</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Name of the identification scheme, in a free text form.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="PostalAddress24__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">PostalAddress24__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Information that locates and identifies a specific address, as defined by postal services.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element maxOccurs="1" minOccurs="0" name="Dept" type="Max70Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Department</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Identification of a division of a large organisation or building.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="SubDept" type="Max70Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">SubDepartment</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Identification of a sub-division of a large organisation or building.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="StrtNm" type="Max70Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">StreetName</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Name of a street or thoroughfare.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="BldgNb" type="Max16Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">BuildingNumber</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Number that identifies the position of a building on a street.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="BldgNm" type="Max35Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">BuildingName</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Name of the building or house.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="Flr" type="Max70Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Floor</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Floor or storey within a building.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="PstBx" type="Max16Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">PostBox</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Numbered box in a post office, assigned to a person or organisation, where letters are kept until called for.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="Room" type="Max70Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Room</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Building room number.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="PstCd" type="Max16Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">PostCode</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Identifier consisting of a group of letters and/or numbers that is added to a postal address to assist the sorting of mail.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="TwnNm" type="Max35Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">TownName</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Name of a built-up area, with defined boundaries, and a local government.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="TwnLctnNm" type="Max35Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">TownLocationName</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Specific location name within the town.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="DstrctNm" type="Max35Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">DistrictName</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Identifies a subdivision within a country sub-division.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="CtrySubDvsn" type="Max35Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">CountrySubDivision</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Identifies a subdivision of a country such as state, region, county.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="Ctry" type="CountryCode">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Country</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Nation with its own government.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="3" minOccurs="0" name="AdrLine" type="Max35Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">AddressLine</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Information that locates and identifies a specific address, as defined by postal services, presented in free format text.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="StatusReason6Choice__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">StatusReason6Choice__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Specifies the reason for the status of the transaction.</xs:documentation>
        </xs:annotation>
        <xs:choice>
            <xs:element name="Cd" type="ExternalStatusReason1Code">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Code</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Reason for the status, as published in an external reason code list.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="StatusReasonInformation12__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">StatusReasonInformation12__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Provides information on the status reason of the transaction.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element maxOccurs="1" minOccurs="0" name="Orgtr" type="PartyIdentification135__2">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Originator</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Party that issues the status.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="Rsn" type="StatusReason6Choice__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Reason</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Specifies the reason for the status report.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="2" minOccurs="0" name="AddtlInf" type="Max105Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">AdditionalInformation</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Further details on the status reason.

Usage: Additional information can be used for several purposes such as the reporting of repaired information.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="UUIDv4Identifier">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">UUIDv4Identifier</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Universally Unique IDentifier (UUID) version 4, as described in IETC RFC 4122 "Universally Unique IDentifier (UUID) URN Namespace".</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>
