<?xml version="1.0" encoding="UTF-8"?>
<!--- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Legal Notices

SWIFT SCRL@2016. All rights reserved.

This schema is a component of MyStandards, the SWIFT collaborative Web application used to manage
standards definitions and industry usage.

This is a licensed product, which may only be used and distributed in accordance with MyStandards License
Terms as specified in MyStandards Service Description and the related Terms of Use.

Unless otherwise agreed in writing with SWIFT SCRL, the user has no right to:
 - authorise external end users to use this component for other purposes than their internal use.
 - remove, alter, cover, obfuscate or cancel from view any copyright or other proprietary rights notices appearing in this physical medium.
 - re-sell or authorise another party e.g. software and service providers, to re-sell this component.

This component is provided 'AS IS'. SWIFT does not give and excludes any express or implied warranties
with respect to this component such as but not limited to any guarantee as to its quality, supply or availability.

Any and all rights, including title, ownership rights, copyright, trademark, patents, and any other intellectual 
property rights of whatever nature in this component will remain the exclusive property of SWIFT or its 
licensors.

Trademarks
SWIFT is the trade name of S.W.I.F.T. SCRL.
The following are registered trademarks of SWIFT: the SWIFT logo, SWIFT, SWIFTNet, SWIFTReady, Accord, Sibos, 3SKey, Innotribe, the Standards Forum logo, MyStandards, and SWIFT Institute.
Other product, service, or company names in this publication are trade names, trademarks, or registered trademarks of their respective owners.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Group: FedNow Service
Collection: FedNow Service Release 1
Usage Guideline: PaymentStatusRequest_pacs.028.001.03
Base Message: pacs.028.001.03
Date of publication: 08 April 2022
URL: https://www2.swift.com/mystandards/#/mp/mx/_kijaUKEYEeuB-v2uhrZqSw/_rz7AUZ5FEeyNX8SYmSuaLA
Description: FedNow Service Scope

A payment status request is the message the FedNow participant uses to request the FedNow Service or another FedNow participant to (re)send the processing status (positive, pending, negative...) of a payment or request for payment message previously sent through the FedNow Service.  

FedNow Service Usage

A FedNow participant may use the payment status request message to query the FedNow Service about the processing status of a previously sent customer credit transfer (pacs.008), payment return (pacs.004), or financial institution credit transfer (pacs.009) message, or query a FedNow participant about the processing status of a previously sent customer credit transfer (pacs.008), payment return (pacs.004), or request for payment (pain.013) message. 

The FedNow Service will use the payment status report (pacs.002) message to inform about the processing status of a previously sent payment message (pacs.008, pacs.004, or pacs.009) for which a payment status was requested. A FedNow participant can only request the FedNow Service for a payment status of a previously sent or received message for the current or prior calendar day. Furthermore, requests should not be sent before the presumed timeout of the payment instruction. 
 
The FedNow participant will use the payment status report (pacs.002) message to inform about the processing status of a previously sent payment message (pacs.008 or pacs.004) for which a payment status was requested, or the request for payment response (pain.014) message to inform about the processing status of a previously sent request for payment (pain.013) message for which a payment status was requested.
Generated by the MyStandards web platform [https://www.swift.com/mystandards] on 2022-04-14T19:45:35+00:00
-->
<!---->
<xs:schema xmlns="urn:iso:std:iso:20022:tech:xsd:pacs.028.001.03" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="urn:iso:std:iso:20022:tech:xsd:pacs.028.001.03">
    <xs:element name="Document" type="Document"/>
    <xs:complexType name="BranchAndFinancialInstitutionIdentification6__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">BranchAndFinancialInstitutionIdentification6__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Unique and unambiguous identification of a financial institution or a branch of a financial institution.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="FinInstnId" type="FinancialInstitutionIdentification18__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">FinancialInstitutionIdentification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Unique and unambiguous identification of a financial institution, as assigned under an internationally recognised or proprietary identification scheme.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="ClearingSystemIdentification2Choice__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">ClearingSystemIdentification2Choice__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Choice of a clearing system identifier.</xs:documentation>
        </xs:annotation>
        <xs:choice>
            <xs:element name="Cd" type="ExternalClearingSystemIdentification1Code_fixed">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Code</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Identification of a clearing system, in a coded form as published in an external list.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="ClearingSystemMemberIdentification2__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">ClearingSystemMemberIdentification2__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Unique identification, as assigned by a clearing system, to unambiguously identify a member of the clearing system.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="ClrSysId" type="ClearingSystemIdentification2Choice__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">ClearingSystemIdentification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Specification of a pre-agreed offering between clearing agents or the channel through which the payment instruction is processed.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="MmbId" type="RoutingNumber_FRS_1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">MemberIdentification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Identification of a member of a clearing system.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Document">
        <xs:sequence>
            <xs:element name="FIToFIPmtStsReq" type="FIToFIPaymentStatusRequestV03"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="ExternalClearingSystemIdentification1Code_fixed">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">ExternalClearingSystemIdentification1Code_fixed</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:enumeration value="USABA">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">USABA</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="FIToFIPaymentStatusRequestV03">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">FIToFIPaymentStatusRequestV03</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Scope&#13;
The FinancialInstitutionToFinancialInstitutionPaymentStatusRequest message is sent by the debtor agent to the creditor agent, directly or through other agents and/or a payment clearing and settlement system. It is used to request a FIToFIPaymentStatusReport message containing information on the status of a previously sent instruction. &#13;
Usage&#13;
The FIToFIPaymentStatusRequest message is exchanged between agents to request status information about instructions previously sent. Its usage will always be governed by a bilateral agreement between the agents.&#13;
The FIToFIPaymentStatusRequest message can be used to request information about the status (e.g. rejection, acceptance) of a credit transfer instruction, a direct debit instruction, as well as other intra-agent instructions (for example FIToFIPaymentCancellationRequest).&#13;
The FIToFIPaymentStatusRequest message refers to the original instruction(s) by means of references only or by means of references and a set of elements from the original instruction.&#13;
The FIToFIPaymentStatusRequest message can be used in domestic and cross-border scenarios.&#13;
&#13;
</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="GrpHdr" type="GroupHeader91__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">GroupHeader</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Set of characteristics shared by all individual transactions included in the status request message.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="TxInf" type="PaymentTransaction113__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">TransactionInformation</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Information concerning the original transaction, to which the status request message refers.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="FinancialInstitutionIdentification18__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">FinancialInstitutionIdentification18__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Specifies the details to identify a financial institution.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="ClrSysMmbId" type="ClearingSystemMemberIdentification2__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">ClearingSystemMemberIdentification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Information used to identify a member within a clearing system.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="GroupHeader91__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">GroupHeader91__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Set of characteristics shared by all individual transactions included in the message.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="MsgId" type="MessageIdentification_FedNow_1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">MessageIdentification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Point to point reference, as assigned by the instructing party, and sent to the next party in the chain to unambiguously identify the message.
Usage: The instructing party has to make sure that MessageIdentification is unique per instructed party for a pre-agreed period.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="CreDtTm" type="ISODateTime">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">CreationDateTime</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Date and time at which the message was created.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="ISODateTime">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">ISODateTime</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">A particular point in the progression of time defined by a mandatory date and a mandatory time component, expressed in either UTC time format (YYYY-MM-DDThh:mm:ss.sssZ), local time with UTC offset format (YYYY-MM-DDThh:mm:ss.sss+/-hh:mm), or local time format (YYYY-MM-DDThh:mm:ss.sss). These representations are defined in "XML Schema Part 2: Datatypes Second Edition - W3C Recommendation 28 October 2004" which is aligned with ISO 8601.
Note on the time format:
1) beginning / end of calendar day
00:00:00 = the beginning of a calendar day
24:00:00 = the end of a calendar day
2) fractions of second in time format
Decimal fractions of seconds may be included. In this case, the involved parties shall agree on the maximum number of digits that are allowed.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:dateTime"/>
    </xs:simpleType>
    <xs:simpleType name="Max35Text">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">Max35Text</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Specifies a character string with a maximum length of 35 characters.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="35"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="MessageIdentification_FedNow_1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">MessageIdentification_FedNow_1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">The FedNow Message Identification is a reference assigned by the sender of the message, and is composed of the Calendar Date (8 numerical characters, CCYYMMDD), the sender's FedNow Connection Party Identification (9 alphanumerical characters), and a reference assigned by the sender (up to 18 characters permissible for a text element). </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:minLength value="18"/>
            <xs:maxLength value="35"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="OriginalGroupInformation29__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">OriginalGroupInformation29__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Unique and unambiguous identifier of the group of transactions as assigned by the original instructing party.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="OrgnlMsgId" type="Max35Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">OriginalMessageIdentification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Point to point reference assigned by the original instructing party to unambiguously identify the original message.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="OrgnlMsgNmId" type="Max35Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">OriginalMessageNameIdentification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Specifies the original message name identifier to which the message refers, for example, pacs.003.001.01 or MT103.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="OrgnlCreDtTm" type="ISODateTime">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">OriginalCreationDateTime</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Original date and time at which the message was created.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="PaymentTransaction113__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">PaymentTransaction113__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Provides further details on the original transactions, to which the status report message refers.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="OrgnlGrpInf" type="OriginalGroupInformation29__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">OriginalGroupInformation</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Point to point reference, as assigned by the original instructing party, to unambiguously identify the original message.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="OrgnlInstrId" type="Max35Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">OriginalInstructionIdentification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Unique identification, as assigned by the original instructing party for the original instructed party, to unambiguously identify the original instruction.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="OrgnlEndToEndId" type="Max35Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">OriginalEndToEndIdentification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Unique identification, as assigned by the original initiating party, to unambiguously identify the original transaction.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="OrgnlTxId" type="Max35Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">OriginalTransactionIdentification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Unique identification, as assigned by the original first instructing agent, to unambiguously identify the transaction.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="OrgnlUETR" type="UUIDv4Identifier">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">OriginalUETR</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Universally unique identifier to provide the original end-to-end reference of a payment transaction.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="InstgAgt" type="BranchAndFinancialInstitutionIdentification6__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">InstructingAgent</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Agent that instructs the next party in the chain to carry out the (set of) instruction(s).&#13;
&#13;
</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="InstdAgt" type="BranchAndFinancialInstitutionIdentification6__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">InstructedAgent</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Agent that is instructed by the previous party in the chain to carry out the (set of) instruction(s).&#13;
&#13;
</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="RoutingNumber_FRS_1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">RoutingNumber_FRS_1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">This is a routing number used by the Service participant in connection with the message.&#13;
&#13;
Note: This may be a master account routing number or a subaccount routing number. </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{9,9}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="UUIDv4Identifier">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">UUIDv4Identifier</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Universally Unique IDentifier (UUID) version 4, as described in IETC RFC 4122 "Universally Unique IDentifier (UUID) URN Namespace".</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>
